image: ubuntu:22.04

pages:
  stage: deploy
  tags:
    - docker
  script:
    - apt-get update && apt-get install -y curl gdebi-core
    - curl -LO https://github.com/quarto-dev/quarto-cli/releases/latest/download/quarto-linux-amd64.deb
    - gdebi --non-interactive quarto-linux-amd64.deb
    - quarto render
    - mv _site public
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'